language: python
python:
  - '3.7'
install:
  - python -m pip install --upgrade pip
  - pip --version
script:
  - python -c "print('Hello Travis')"
deploy:
  provider: pypi
  user: bmmauri
  password:
    secure: MTaHzCAacnQZVxRuedTRrnPgafbwpGNV5iODn05nAazf/8qJD8SXxD96Al5r8hA6VkNovBzbLDBrj6O1b++gJpWZpgIM3yQ3kXlyqAtahNAiiPIJHfzvaVugAilwETQKPUKbXVWEdf2IUaSyoHFcf3nqQKQP+3ezvVyoMMDtEl3Xc9Aw5yyN0x573qKlRpmeHVWoBndGVbpYgROdUsYWpjJCkYXlDWyg4MmLXrRYrI+mObm8K3OyJiGAgfk9PHGDUYPBD9OtV/mI08QnknlkvK1ZVWHD9Jm/lxl3I/yJ0nYXiPBfT9NKoNqbUZ2uUhhEe41mn5NxvL/P1XVu7484zbzNZ8wfHu7CgAaqnlo8ANJvFi6W8uunW2iooWhdsS4ko1QLVRbkpXAcTI/QzbbznxqSAARlR6fqQLp26y+dKs0P3Elx6bigMkw6PKLF/z+Ryg4tFIemf+gO3KGqUVNM+UG4NnJitdAH60SbvuF8qsr1twv8rJQF6xDfChPyuVXKsSLvhNvm0rkNqPGb9kmKdxSL7HWkOxwsjNvOEpdtSJLNQKa/3a+5I5L0iS9ydzZYHjtfTBLojQAc7GPgAWKJ3cPHciVhIW3VOozRALDcSI3jamO3mY0DQKqF8kh6L9r0ViFqG65nNPVbgOw128nz3P7wlQR7LZEBPfTvPk+/tcQ=
  server: https://test.pypi.org/legacy/
  on:
    branch: master
  skip_cleanup: true
  skip_existing: true
