language: python
python:
  - '3.7'
  - '3.8'
  - 3.8-dev
  - nightly
script:
  - python -c "print('Hello Travis')"
deploy:
  provider: pypi
  username: __token__
  password:
    secure: FmRSASEPalRBNdltMcLd9lEBuMVK6Iv2ZT/JcG4SflGwihnntczhiFzYJWc1wwdPLmbUDUxqNfCce7AvvJWye1NbXiN6B4JX/g7F+DDcnC28a4mk3hQNHZUZ4LRZDJHpxnf6z8gneELva1A4FZ6QZylbS1u73V1J+aJXdkS6APtvqmDxG3IbHt8dBlHDmgZ9JtertVSIZqmdnLF1Nthr68+rnluhLT49rzjhAJBE/GmAJECvlVX+hwJAs6H9qScYbCjW9+u2O/ajclgdJV0GD1V5T6oFUH9+5KtyVgkOmJ9u6zgRJeP2WR3WaUxn0/lQ2plZI+eaiERlNIBv9MknFXmB4xXtnqkb/quUra7ixDoUySUgn3tY5WV4zDb/iF3MXO5P73K2J1UOD2oeOqOD6Y0MKq77rYpdAkbOQuG+6mZDua+6wu02c2GGkcjJZCAd3WMy/xpk2/5Iu3aphv4QJAzq6PNS4QzR8C/N9t6V5T9TliDyLICm7WfgJmF+rpTUMwRQVcV5bwDY5vPLLJqOClEptFPLo35UaJY565JEJ2cLzInwxOQvWBxRzpLJWSIyHzTtLIwAsoZ7vgwUiMwtFrAkLsgy7SUqckIjGYFmXYhl1FpxpIpTJN09ODyk9P6Bx+R809zIvuQqRqyHt5SWsxMD2CLkJfwDqa3uwlHCE/o=
  server: https://test.pypi.org/legacy/
  on:
    branch: master
