language: python
python:
  - '3.7'
  - '3.8'
  - 3.8-dev
  - nightly
#install:
#  - pip install .
script:
  - pytest
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "Wqh0jQD3Ij7NicSaM1ZIraO5QgtXCPyFhLR8emv6o0v/KkJW2o5ZvzgW3Gd5bdalOTjNR3HxGZdeYORQ/15ZmtQjNzFuefOHIZg1OLfdnZHa4rT4y7Y/x3oNwnLtXr7QzPvFvfijDHwum5q2zgtaQ04gJsvU4KGx0Yno0ijcAVumpttlj6ZMBEgyoJI8LlKLKsywBwJuIPkaprVjkoISJjBZYbbtuv7jDzcUxMXhB/DQ0hN3upB4U7NGtWSsHWIBbpLFcNAq38jbmHwhObfukLOxeSW6ED/gR034sRU/W61owj0VqzxR3IPpM9wJAOjFfs6qc/FEQd39ijitsJgfSYEdYPq+rFpqtJeaT/6GUC16U867+RRUh4hxvQJnca2eOSm86OcNNBjuk31xu9vn3VFueKE82ffiojtNp2hIYLG1twSXQg9M50lscTNb7boq1bKOFmlzNw4V34eSQoapnjuCyITojDj8KnkRp+xkV3oo20DPcptLUlIPGjlB7vmrx4pepIhxeH0WZSncCN8wkluxLzf26Lj6pzvax5nHg09sgQ3WB6ioesSwj1qI38Dmp+DiPSNMiDrRuyF1LpZ3e1Q4xU9XmM8DM1ONMDuh/niw/b+13qaO9wv5tbi1Gm6xeR4bNcWetQEV6xkuhzcprx+hPuzqGL3yX1tSigAvqNk="
  server: https://testpypi.python.org/pypi
  on:
    tags: true
