language: python
python:
- '3.7'
- '3.8'
- 3.8-dev
- nightly
install:
- python -m pip install --upgrade pip
- pip --version
script:
- python -c "print('Hello Travis')"
deploy:
  provider: pypi
  user: bmmauri
  password:
    secure: weCXEjBEXsdVh9SvsRIC08FYWURcUrGjOei8IosvZ6SewEx45591WSoVMcgW+k+yrDPCgFYCVQ9xGBcnAlUnBd9GG8w+spKhY3SCQbAjnMumFO0J7blXmdRD6BZZZsad32lcMcz5rQEsBp0gBsfASVTWnzM6bJP4Wfsa3Sair/47TsGHN9ev8G5TCkEKA0KkIAAa0ZUKSic630dEbFSvqabfn4taz7mmb13vHfjppM56j7qQEvK4jI3FSbnKnM5LPWeXywhhRBnUrLSJ4v58w0DpAzjralcfOS5MWfrCmVqSpDBHU4NB5Okyhg0mM8A41D65Qisah8caI90kxAJYg3htRaZSxXHHjlS1w535d1+7z+fSks4LjHnX42Q0R3kRY+JRMfPmMXdVY16Ay/ACry3tQrjwBcunQJOZBJ7hGZElWNIph/WZDhWu9Y1SkdAb7zJz4HB/v8f02FHxcduQXg36s63xsCp64KmtYAvPP6FfuBtZ7S2nYZawR8DlWPpGKqF1A09Q95ca5pAdZVv9zry0AhyylxTHHBz/lMH4SHbUS7lU+OiMc56FfdC8NU0BY+pNAgM36r6h5rAEpF9cj5teXtomIwtVJxHf8arseH5h2Nnm3/qtT7UOGmHHZP7lvJcpLP9+yDY9f8Ub2Cf9uuj42LXfOVNrspDCqu0FSi4=
  server: https://test.pypi.org/legacy/
  on:
    branch: master
